// backend/src/config/mockDbData.js
// Full seed data for the local mock database fallback
// Matches database/seed.sql exactly — 18 properties, 12 users, reviews, bookings, notifications

export const INITIAL_DB_STATE = {
  users: [
    {
      user_id: 1,
      full_name: "System Administrator",
      email: "admin@hostelportal.edu.gh",
      phone: "+233241000000",
      password_hash: "$2a$12$ZWRFO0Sm4Tu22P27ZjKhfumg0ny970SH9ywyaJjus0bTZ8huyoto2", // Admin@1234
      role: "Admin",
      verification_status: "Approved",
      id_document_path: null,
      is_active: true,
      created_at: new Date(Date.now() - 37 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      user_id: 2,
      full_name: "Kwame Asante Boateng",
      email: "kwame.asante@gmail.com",
      phone: "+233244123456",
      password_hash: "$2a$12$Dwt6ACQDQj3uaHjUa97cD.IeB9YiQI1YXA/yFZYaJ5n3IYAAa5J1y", // Landlord@1
      role: "Landlord",
      verification_status: "Approved",
      id_document_path: null,
      profile_picture: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400",
      bio: "Experienced student housing provider near KTU campus. Committed to providing clean, safe, and comfortable off-campus accommodations for over 6 years.",
      is_active: true,
      created_at: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      user_id: 3,
      full_name: "Abena Mensah Osei",
      email: "abena.mensah@gmail.com",
      phone: "+233205678901",
      password_hash: "$2a$12$Dwt6ACQDQj3uaHjUa97cD.IeB9YiQI1YXA/yFZYaJ5n3IYAAa5J1y",
      role: "Landlord",
      verification_status: "Approved",
      id_document_path: null,
      is_active: true,
      created_at: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      user_id: 4,
      full_name: "Kofi Darko Amponsah",
      email: "kofi.darko@gmail.com",
      phone: "+233209876543",
      password_hash: "$2a$12$Dwt6ACQDQj3uaHjUa97cD.IeB9YiQI1YXA/yFZYaJ5n3IYAAa5J1y",
      role: "Landlord",
      verification_status: "Approved",
      id_document_path: null,
      is_active: true,
      created_at: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      user_id: 5,
      full_name: "Ama Serwaa Asante",
      email: "ama.serwaa@gmail.com",
      phone: "+233244567890",
      password_hash: "$2a$12$Dwt6ACQDQj3uaHjUa97cD.IeB9YiQI1YXA/yFZYaJ5n3IYAAa5J1y",
      role: "Landlord",
      verification_status: "Approved",
      id_document_path: null,
      is_active: true,
      created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      user_id: 6,
      full_name: "Yaw Frimpong Boahen",
      email: "yaw.frimpong@gmail.com",
      phone: "+233200112233",
      password_hash: "$2a$12$Dwt6ACQDQj3uaHjUa97cD.IeB9YiQI1YXA/yFZYaJ5n3IYAAa5J1y",
      role: "Landlord",
      verification_status: "Pending",
      id_document_path: null,
      is_active: true,
      created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      user_id: 7,
      full_name: "Esi Adjoa Quaye",
      email: "esi.quaye@ktu.edu.gh",
      phone: "+233554321098",
      password_hash: "$2a$12$6bRal0l/UfYDJnooLMRY4.0HAvqCymBdSx0yKrmomhmJ4Jsfj/v1S", // Student@1
      role: "Student",
      verification_status: "Approved",
      id_document_path: null,
      is_active: true,
      created_at: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      user_id: 8,
      full_name: "Emmanuel Owusu Ansah",
      email: "emmanuel.owusu@ktu.edu.gh",
      phone: "+233503456789",
      password_hash: "$2a$12$6bRal0l/UfYDJnooLMRY4.0HAvqCymBdSx0yKrmomhmJ4Jsfj/v1S",
      role: "Student",
      verification_status: "Approved",
      id_document_path: null,
      is_active: true,
      created_at: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      user_id: 9,
      full_name: "Akosua Agyemang",
      email: "akosua.agyemang@ktu.edu.gh",
      phone: "+233244987654",
      password_hash: "$2a$12$6bRal0l/UfYDJnooLMRY4.0HAvqCymBdSx0yKrmomhmJ4Jsfj/v1S",
      role: "Student",
      verification_status: "Approved",
      id_document_path: null,
      is_active: true,
      created_at: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      user_id: 10,
      full_name: "Kojo Mensah Acheampong",
      email: "kojo.mensah@ktu.edu.gh",
      phone: "+233271234567",
      password_hash: "$2a$12$6bRal0l/UfYDJnooLMRY4.0HAvqCymBdSx0yKrmomhmJ4Jsfj/v1S",
      role: "Student",
      verification_status: "Approved",
      id_document_path: null,
      is_active: true,
      created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      user_id: 11,
      full_name: "Adwoa Pokuaa Ntiamoah",
      email: "adwoa.pokuaa@ktu.edu.gh",
      phone: "+233246543210",
      password_hash: "$2a$12$6bRal0l/UfYDJnooLMRY4.0HAvqCymBdSx0yKrmomhmJ4Jsfj/v1S",
      role: "Student",
      verification_status: "Approved",
      id_document_path: null,
      is_active: true,
      created_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      user_id: 12,
      full_name: "Bright Asare Frimpong",
      email: "bright.asare@ktu.edu.gh",
      phone: "+233509876543",
      password_hash: "$2a$12$6bRal0l/UfYDJnooLMRY4.0HAvqCymBdSx0yKrmomhmJ4Jsfj/v1S",
      role: "Student",
      verification_status: "Approved",
      id_document_path: null,
      is_active: true,
      created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString()
    }
  ],
  properties: [
    // Kwame's properties (landlord_id = 2)
    {
      property_id: 1,
      landlord_id: 2,
      title: "Asante Court – Single Rooms",
      address: "Adweso Junction, Koforidua",
      latitude: 6.0882,
      longitude: -0.2541,
      description: "Bright single rooms 5 minutes walk from KTU main gate. 24/7 security, borehole water, and reliable electricity. Suitable for serious students.",
      price_per_semester: 550,
      room_type: "Single, Shared",
      max_occupancy: 2,
      room_rates: '[{"room_type":"Single","price_per_semester":850,"max_occupancy":1},{"room_type":"Shared","price_per_semester":550,"max_occupancy":2}]',
      amenities: '["Running Water","Security","WiFi","Study Desk","Ceiling Fan","Security Light"]',
      neighborhood: "Adweso",
      distance_from_campus_km: 0.8,
      availability_status: "Available",
      verification_status: "Approved",
      created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      property_id: 2,
      landlord_id: 2,
      title: "Asante Court – Shared Rooms",
      address: "Adweso Junction, Koforidua",
      latitude: 6.0884,
      longitude: -0.2543,
      description: "Affordable shared rooms for 2 occupants. Same compound as our Single Rooms. Great community atmosphere.",
      price_per_semester: 550,
      room_type: "Shared",
      max_occupancy: 2,
      amenities: '["Running Water","Security","Study Desk","Ceiling Fan"]',
      neighborhood: "Adweso",
      distance_from_campus_km: 0.9,
      availability_status: "Available",
      verification_status: "Approved",
      created_at: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      property_id: 3,
      landlord_id: 2,
      title: "Asante Self-Contained Apartment",
      address: "Adweso Road, Koforidua",
      latitude: 6.0890,
      longitude: -0.2538,
      description: "Modern self-contained unit with private bathroom and kitchenette. Perfect for students who prefer complete privacy.",
      price_per_semester: 1400,
      room_type: "Self-contained",
      max_occupancy: 1,
      amenities: '["Private Bathroom","Kitchenette","Running Water","Security","WiFi","Air Conditioning","Study Desk"]',
      neighborhood: "Adweso",
      distance_from_campus_km: 0.7,
      availability_status: "Occupied",
      verification_status: "Approved",
      created_at: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString()
    },
    // Abena's properties (landlord_id = 3)
    {
      property_id: 4,
      landlord_id: 3,
      title: "Nsukwao Student Lodge",
      address: "Nsukwao, behind KTU Tech Park",
      latitude: 6.0862,
      longitude: -0.2589,
      description: "Well-maintained student hostel just behind KTU Tech Park. Clean rooms, courtyard with seating area, and generator backup.",
      price_per_semester: 700,
      room_type: "Single",
      max_occupancy: 1,
      amenities: '["Generator Backup","Running Water","Security","WiFi","Laundry Area","Study Desk","Ceiling Fan"]',
      neighborhood: "Nsukwao",
      distance_from_campus_km: 1.2,
      availability_status: "Available",
      verification_status: "Approved",
      created_at: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      property_id: 5,
      landlord_id: 3,
      title: "Nsukwao Budget Rooms",
      address: "Nsukwao Zongo Road, Koforidua",
      latitude: 6.0858,
      longitude: -0.2601,
      description: "Budget-friendly shared accommodation for cost-conscious students. Shared kitchen available.",
      price_per_semester: 400,
      room_type: "Shared",
      max_occupancy: 2,
      amenities: '["Shared Kitchen","Ceiling Fan","Security"]',
      neighborhood: "Nsukwao",
      distance_from_campus_km: 1.5,
      availability_status: "Available",
      verification_status: "Approved",
      created_at: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      property_id: 6,
      landlord_id: 3,
      title: "Mensah Premium Apartments",
      address: "Nsukwao Main Road, Koforidua",
      latitude: 6.0870,
      longitude: -0.2575,
      description: "Premium 1-bedroom apartments for postgraduate students or those seeking a higher standard of living near KTU.",
      price_per_semester: 2200,
      room_type: "Apartment",
      max_occupancy: 2,
      amenities: '["Private Bathroom","Full Kitchen","Air Conditioning","WiFi","Security","Parking","Generator Backup"]',
      neighborhood: "Nsukwao",
      distance_from_campus_km: 1.0,
      availability_status: "Available",
      verification_status: "Approved",
      created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString()
    },
    // Kofi's properties (landlord_id = 4)
    {
      property_id: 7,
      landlord_id: 4,
      title: "Effiduase Student Chambers",
      address: "Effiduase Road, Near KTU",
      latitude: 6.0935,
      longitude: -0.2620,
      description: "Spacious chambers in Effiduase, popular with engineering students. Motorcycle hire available nearby.",
      price_per_semester: 600,
      room_type: "Single",
      max_occupancy: 1,
      amenities: '["Running Water","Security","Study Desk","Ceiling Fan","Compound Lighting"]',
      neighborhood: "Effiduase",
      distance_from_campus_km: 1.8,
      availability_status: "Available",
      verification_status: "Approved",
      created_at: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      property_id: 8,
      landlord_id: 4,
      title: "Darko Hostel – Economy Shared",
      address: "Effiduase Junction, Koforidua",
      latitude: 6.0940,
      longitude: -0.2615,
      description: "Economy shared rooms for first-year students on a tight budget. Clean, safe, and close to campus.",
      price_per_semester: 350,
      room_type: "Shared",
      max_occupancy: 3,
      amenities: '["Running Water","Security","Ceiling Fan"]',
      neighborhood: "Effiduase",
      distance_from_campus_km: 1.9,
      availability_status: "Available",
      verification_status: "Approved",
      created_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      property_id: 9,
      landlord_id: 4,
      title: "Darko Executive Self-Contained",
      address: "Effiduase, Near Total Filling Station",
      latitude: 6.0925,
      longitude: -0.2630,
      description: "Executive self-contained room with private veranda. Secure compound with CCTV.",
      price_per_semester: 1600,
      room_type: "Self-contained",
      max_occupancy: 1,
      amenities: '["Private Bathroom","CCTV","Security","WiFi","Air Conditioning","Study Desk","Generator Backup"]',
      neighborhood: "Effiduase",
      distance_from_campus_km: 2.0,
      availability_status: "Pending",
      verification_status: "Approved",
      created_at: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString()
    },
    // Ama's properties (landlord_id = 5)
    {
      property_id: 10,
      landlord_id: 5,
      title: "Oyoko Green Hostel",
      address: "Oyoko, Koforidua-Kumasi Road",
      latitude: 6.0820,
      longitude: -0.2480,
      description: "Peaceful hostel set in Oyoko's greenery. Ideal for students who prefer a calm study environment. Trotro direct to KTU gate.",
      price_per_semester: 750,
      room_type: "Single",
      max_occupancy: 1,
      amenities: '["Running Water","Security","Study Desk","WiFi","Ceiling Fan","Quiet Environment"]',
      neighborhood: "Oyoko",
      distance_from_campus_km: 2.5,
      availability_status: "Available",
      verification_status: "Approved",
      created_at: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      property_id: 11,
      landlord_id: 5,
      title: "Oyoko Shared Rooms",
      address: "Oyoko New Road, Koforidua",
      latitude: 6.0815,
      longitude: -0.2475,
      description: "Affordable shared rooms with good security. Regular trotro to KTU available.",
      price_per_semester: 450,
      room_type: "Shared",
      max_occupancy: 2,
      amenities: '["Running Water","Security","Ceiling Fan"]',
      neighborhood: "Oyoko",
      distance_from_campus_km: 2.6,
      availability_status: "Available",
      verification_status: "Approved",
      created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      property_id: 12,
      landlord_id: 5,
      title: "Serwaa Apartments – Studio",
      address: "Ashanti Nkwanta, Koforidua",
      latitude: 6.0910,
      longitude: -0.2500,
      description: "Modern studio apartments in Ashanti Nkwanta. Recently renovated with new fittings. Great value.",
      price_per_semester: 1800,
      room_type: "Apartment",
      max_occupancy: 1,
      amenities: '["Private Bathroom","Kitchenette","Air Conditioning","WiFi","Security","Study Desk","Generator Backup"]',
      neighborhood: "Ashanti Nkwanta",
      distance_from_campus_km: 1.4,
      availability_status: "Available",
      verification_status: "Approved",
      created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      property_id: 13,
      landlord_id: 5,
      title: "Serwaa Classic Self-Contained",
      address: "Ashanti Nkwanta Road, Koforidua",
      latitude: 6.0905,
      longitude: -0.2510,
      description: "Classic self-contained room with large wardrobe and study area. Popular with female students.",
      price_per_semester: 1200,
      room_type: "Self-contained",
      max_occupancy: 1,
      amenities: '["Private Bathroom","Security","Running Water","Ceiling Fan","Study Desk","Wardrobe"]',
      neighborhood: "Ashanti Nkwanta",
      distance_from_campus_km: 1.3,
      availability_status: "Occupied",
      verification_status: "Approved",
      created_at: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      property_id: 14,
      landlord_id: 2,
      title: "Adweso Premium Block B",
      address: "Adweso, Near KTU Engineering Faculty",
      latitude: 6.0877,
      longitude: -0.2548,
      description: "Block B rooms—slightly larger than Block A. Quiet block preferred by final-year students.",
      price_per_semester: 950,
      room_type: "Single",
      max_occupancy: 1,
      amenities: '["Running Water","Security","WiFi","Study Desk","Ceiling Fan","Wardrobe"]',
      neighborhood: "Adweso",
      distance_from_campus_km: 1.0,
      availability_status: "Available",
      verification_status: "Approved",
      created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      property_id: 15,
      landlord_id: 4,
      title: "Akwadum Student Suites",
      address: "Akwadum Road, Koforidua",
      latitude: 6.0960,
      longitude: -0.2650,
      description: "Suites in Akwadum with shared sitting room per floor. Suited for group study sessions.",
      price_per_semester: 800,
      room_type: "Single",
      max_occupancy: 1,
      amenities: '["Shared Sitting Room","Running Water","Security","Study Desk","WiFi"]',
      neighborhood: "Akwadum",
      distance_from_campus_km: 2.8,
      availability_status: "Available",
      verification_status: "Approved",
      created_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      property_id: 16,
      landlord_id: 3,
      title: "Mensah Budget Singles – Nsukwao",
      address: "Nsukwao Lane 3, Koforidua",
      latitude: 6.0865,
      longitude: -0.2595,
      description: "No-frills single rooms at the best price in Nsukwao. Great for budget-conscious students.",
      price_per_semester: 480,
      room_type: "Single",
      max_occupancy: 1,
      amenities: '["Running Water","Security","Ceiling Fan"]',
      neighborhood: "Nsukwao",
      distance_from_campus_km: 1.4,
      availability_status: "Available",
      verification_status: "Approved",
      created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      property_id: 17,
      landlord_id: 5,
      title: "Oyoko Premier Lodge",
      address: "Oyoko, Off Kumasi Road",
      latitude: 6.0810,
      longitude: -0.2460,
      description: "Premier lodge with 24/7 security, borehole, and generator. The most popular hostel in Oyoko.",
      price_per_semester: 1100,
      room_type: "Self-contained",
      max_occupancy: 1,
      amenities: '["Private Bathroom","Generator Backup","Borehole Water","24/7 Security","WiFi","CCTV","Study Desk"]',
      neighborhood: "Oyoko",
      distance_from_campus_km: 3.0,
      availability_status: "Available",
      verification_status: "Approved",
      created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      property_id: 18,
      landlord_id: 6,
      title: "Frimpong New Development",
      address: "Nsukwao Extension, Koforidua",
      latitude: 6.0850,
      longitude: -0.2610,
      description: "Brand new development. 8 self-contained rooms with modern fittings.",
      price_per_semester: 1500,
      room_type: "Self-contained",
      max_occupancy: 1,
      amenities: '["Private Bathroom","Running Water","Security","Study Desk"]',
      neighborhood: "Nsukwao",
      distance_from_campus_km: 1.6,
      availability_status: "Available",
      verification_status: "Pending",
      created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString()
    }
  ],
  property_images: [
    { image_id: 1,  property_id: 1,  image_path: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600", display_order: 0 },
    { image_id: 2,  property_id: 1,  image_path: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600", display_order: 1 },
    { image_id: 3,  property_id: 2,  image_path: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600", display_order: 0 },
    { image_id: 4,  property_id: 3,  image_path: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600", display_order: 0 },
    { image_id: 5,  property_id: 4,  image_path: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600", display_order: 0 },
    { image_id: 6,  property_id: 4,  image_path: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600", display_order: 1 },
    { image_id: 7,  property_id: 5,  image_path: "https://images.unsplash.com/photo-1522156373667-4c7234bbd804?w=600", display_order: 0 },
    { image_id: 8,  property_id: 6,  image_path: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600", display_order: 0 },
    { image_id: 9,  property_id: 6,  image_path: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600", display_order: 1 },
    { image_id: 10, property_id: 7,  image_path: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=600", display_order: 0 },
    { image_id: 11, property_id: 8,  image_path: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600", display_order: 0 },
    { image_id: 12, property_id: 9,  image_path: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600", display_order: 0 },
    { image_id: 13, property_id: 10, image_path: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600", display_order: 0 },
    { image_id: 14, property_id: 10, image_path: "https://images.unsplash.com/photo-1522156373667-4c7234bbd804?w=600", display_order: 1 },
    { image_id: 15, property_id: 11, image_path: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600", display_order: 0 },
    { image_id: 16, property_id: 12, image_path: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600", display_order: 0 },
    { image_id: 17, property_id: 13, image_path: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=600", display_order: 0 },
    { image_id: 18, property_id: 14, image_path: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600", display_order: 0 },
    { image_id: 19, property_id: 15, image_path: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600", display_order: 0 },
    { image_id: 20, property_id: 16, image_path: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600", display_order: 0 },
    { image_id: 21, property_id: 17, image_path: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600", display_order: 0 },
    { image_id: 22, property_id: 18, image_path: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=600", display_order: 0 }
  ],
  bookings: [
    {
      booking_id: 1,
      student_id: 7,
      property_id: 1,
      status: "Approved",
      created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      expires_at: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
      resolved_at: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      booking_id: 2,
      student_id: 8,
      property_id: 4,
      status: "Approved",
      created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
      expires_at: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
      resolved_at: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      booking_id: 3,
      student_id: 9,
      property_id: 6,
      status: "Approved",
      created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      expires_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      resolved_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      booking_id: 4,
      student_id: 10,
      property_id: 2,
      status: "Expired",
      created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      expires_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
      resolved_at: null
    },
    {
      booking_id: 5,
      student_id: 11,
      property_id: 5,
      status: "Declined",
      created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      expires_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      resolved_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      booking_id: 6,
      student_id: 12,
      property_id: 9,
      status: "Pending",
      created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      expires_at: new Date(Date.now() + 22 * 60 * 60 * 1000).toISOString(),
      resolved_at: null
    }
  ],
  reviews: [
    {
      review_id: 1,
      student_id: 7,
      property_id: 1,
      booking_id: 1,
      rating: 5,
      comment: "Excellent hostel! Very clean, the security guard is always on duty. The study desk is a great touch. I renewed for the second semester without hesitation.",
      is_flagged: false,
      created_at: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      review_id: 2,
      student_id: 8,
      property_id: 4,
      booking_id: 2,
      rating: 4,
      comment: "Good rooms and responsive landlord. The WiFi was occasionally slow but overall a pleasant stay. Good value for money in Nsukwao.",
      is_flagged: false,
      created_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      review_id: 3,
      student_id: 9,
      property_id: 6,
      booking_id: 3,
      rating: 5,
      comment: "Best apartment near KTU. The generator never let me down during load-shedding. Highly recommend to any student looking for premium accommodation.",
      is_flagged: false,
      created_at: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString()
    }
  ],
  notifications: [
    {
      notification_id: 1,
      recipient_id: 2,
      type: "BookingRequest",
      message: 'A student has placed a 24-hour hold on "Asante Court – Single Rooms". Review and respond within 24 hours.',
      related_property_id: 1,
      related_booking_id: 1,
      is_read: true,
      delivery_channel: "InApp",
      created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      notification_id: 2,
      recipient_id: 7,
      type: "BookingAccepted",
      message: 'Great news! Your reservation hold for "Asante Court – Single Rooms" has been accepted. Contact landlord: +233244123456.',
      related_property_id: 1,
      related_booking_id: 1,
      is_read: true,
      delivery_channel: "InApp",
      created_at: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      notification_id: 3,
      recipient_id: 3,
      type: "VerificationResult",
      message: "Your landlord account has been verified and approved. You can now create property listings.",
      related_property_id: null,
      related_booking_id: null,
      is_read: true,
      delivery_channel: "InApp",
      created_at: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      notification_id: 4,
      recipient_id: 4,
      type: "BookingRequest",
      message: 'A student has placed a 24-hour hold on "Darko Executive Self-Contained". Respond before it expires.',
      related_property_id: 9,
      related_booking_id: 6,
      is_read: false,
      delivery_channel: "InApp",
      created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString()
    },
    {
      notification_id: 5,
      recipient_id: 12,
      type: "System",
      message: 'Your reservation hold for "Darko Executive Self-Contained" is active. The landlord has 24 hours to respond.',
      related_property_id: 9,
      related_booking_id: 6,
      is_read: false,
      delivery_channel: "InApp",
      created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString()
    }
  ],
  vacancy_alerts: []
};
